#!/bin/bash
#date 07/09/2021
#author "Idan Cohen"
#purpose "sela devops course"

#GETTING PASSWORD INPUT FROM THE USER
PASS_USER=$1
WARNING='\e[31m';
SUCCESS='\e[32m';
CLEAR='\e[33m';

#ANTHER OPTION FOR USER INPUT
# clear;read -s -p"Password: " PASS_USER;clear;echo "You enter $PASS_USER"


#CHECKING PASSWORD LENGTH
if [ ${#PASS_USER} -lt 10 ]; then
        echo -e $WARNING"\n Error: $PASS_USER you need to enter 10 cherchters at your password."
            exit 1
else
    echo -e $SUCCESS"The password is in the correct length"
fi


#CHECKING PASSWORD INPUT
echo $PASS_USER | grep "[a-z]" | grep "[A-Z]" | grep "[0-9]"
if [[ $? -ne 0 ]];then
echo -e $WARNING"Error: Password need to contain at least 1 upper-case, lower-case, and digits"
    exit 1
fi

echo -e $SUCCESS"The password passed the test."
exit 0;


